name: Build code and push revision to S3

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Checkout
      uses: actions/checkout@v2
    - name: Push revision
      run: |
        zip -r CodeDeployDemo.zip ./ -x *.git* *.github*
        aws s3 cp CodeDeployDemo.zip s3://codedeploy-release-artifacts-demo/CodeDeployDemo.zip
        aws deploy register-application-revision \
          --application-name CodeDeployDemo \
          --s3-location bucket=codedeploy-release-artifacts-demo,key=CodeDeployDemo.zip,bundleType=zip \
          --description ${{ github.sha }}
