name: Deploy latest application revision

on:
  workflow_run:
    workflows: [Build code and push revision to S3]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy using CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name CodeDeployName \
          --deployment-group-name CodeDeployDemoGroup \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --s3-location bucket=codedeploy-release-artifacts-demo,key=CodeDeployDemo.zip,bundleType=zip
  abort:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    - run: echo 'Build failed - abort deployment'
